export type ConfirmationCertLabels = {
  title: string;
  certifyIntro: string;
  son: string;
  daughter: string;
  child: string;
  dateOfBirth: string;
  dateOfConfirmation: string;
  placeOfConfirmation: string;
  celebratedBy: string;
  sponsor: string;
  registerNo: string;
  pageNo: string;
  bookNo: string;
  certificateNo: string;
  issuedOn: string;
  placeOfIssue: string;
  parishPriest: string;
  verifyQr: string;
  father: string;
  mother: string;
};

export type ConfirmationCertViewModel = {
  labels: ConfirmationCertLabels;
  dioceseName: string;
  parishName: string;
  parishLocation: string;
  candidateName: string;
  confirmationName: string;
  childRelation: 'Son' | 'Daughter' | 'Child';
  fatherName: string;
  motherName: string;
  birthDate: string;
  confirmationDate: string;
  placeOfConfirmation: string;
  celebratedBy: string;
  sponsor: string;
  registerNo: string;
  pageNo: string;
  bookNo: string;
  certificateNo: string;
  issuedOn: string;
  placeOfIssue: string;
  serialNumber: string;
  verificationId: string;
  verificationUrl: string;
  digitalHash: string;
  qrDataUrl?: string;
  priestName: string;
};
