import type { NavItem } from '@bcl/ui';

/** Maps hardcoded English nav labels to erp.json keys. */
const NAV_KEY_MAP: Record<string, string> = {
  Diocese: 'sections.diocese',
  Parish: 'sections.parish',
  Sacraments: 'sections.sacraments',
  Pastoral: 'sections.pastoral',
  Liturgy: 'sections.liturgy',
  Finance: 'sections.finance',
  Community: 'sections.community',
  Communication: 'sections.communication',
  'Website CMS': 'nav.cms',
  Settings: 'sections.settings',
  Administration: 'sections.administration',
  'Diocese Dashboard': 'nav.dioceseDashboard',
  Parishes: 'nav.parishes',
  Priests: 'nav.priests',
  'Life Timeline': 'nav.lifeTimeline',
  Congregations: 'nav.congregations',
  Institutions: 'nav.institutions',
  Deaneries: 'nav.deaneries',
  'Diocese Profile': 'nav.dioceseProfile',
  'Theme Engine': 'nav.appearance',
  Languages: 'nav.languages',
  'Pastoral Reports': 'nav.pastoralReports',
  Analytics: 'nav.analytics',
  Baptism: 'nav.baptism',
  Marriage: 'nav.marriage',
  Confirmation: 'nav.confirmation',
  'Holy Communion': 'nav.holyCommunion',
  'Death Register': 'nav.deathRegister',
  Certificates: 'nav.certificates',
  'Digital Books': 'nav.registers',
  Families: 'nav.families',
  Members: 'nav.members',
  'Mass Schedule': 'nav.mass',
  'Hall Booking': 'nav.hallBooking',
  Accommodation: 'nav.accommodation',
  Calendar: 'nav.calendar',
  Catechism: 'nav.catechism',
  Communications: 'nav.communications',
  'App Control Center': 'nav.appControl',
  Cemetery: 'nav.cemetery',
  'Users & Roles': 'nav.rbac',
  'Audit Log': 'nav.audit',
  'Backup / Migration': 'nav.migration',
  'AI Assistant': 'nav.aiAssistant',
  Dashboard: 'nav.dashboard',
  Organizations: 'nav.organizations',
  'Small Christian Communities': 'nav.scc',
  Collections: 'nav.collections',
  Donations: 'nav.donations',
  Accounts: 'nav.accounts',
  Expenses: 'nav.expenses',
  Budgets: 'nav.budgets',
  Reports: 'nav.reportsShort',
  Youth: 'nav.youth',
  Women: 'nav.women',
  Men: 'nav.men',
  BCC: 'nav.bcc',
  Volunteers: 'nav.volunteers',
  SMS: 'nav.sms',
  WhatsApp: 'nav.whatsapp',
  Email: 'nav.email',
  'App Control': 'nav.appControlShort',
  'Daily Liturgy': 'nav.readings',
  'Push Composer': 'nav.pushComposer',
  Announcements: 'nav.announcements',
  Homepage: 'nav.homepage',
  Pages: 'nav.pages',
  Gallery: 'nav.gallery',
  News: 'nav.news',
  Events: 'nav.events',
  Menus: 'nav.menus',
  Media: 'nav.media',
  SEO: 'nav.seo',
  'Theme & Preferences': 'nav.appearance',
  Theme: 'nav.theme',
  Domains: 'nav.domains',
  'Parish Profile': 'nav.parishProfile',
  Users: 'nav.users',
  Permissions: 'nav.permissions',
  Backup: 'nav.backup',
  Integrations: 'nav.integrations',
  Intentions: 'nav.intentions',
  'Prayer Requests': 'nav.prayerRequests',
  Choir: 'nav.choir',
  'Liturgical Groups': 'nav.liturgicalGroups',
};

export function translateNavItems(
  items: NavItem[],
  t: (key: string) => string,
): NavItem[] {
  return items.map((item) => {
    const key = NAV_KEY_MAP[item.label];
    const label = key ? t(key) : item.label;
    return {
      ...item,
      label,
      children: item.children ? translateNavItems(item.children, t) : undefined,
    };
  });
}
